import fs from "fs";
import path from "path";
import { GUARD_CONFIG } from "../config/guard.config";
import { evalService } from "../services/eval.service";

async function main() {
  const report = await evalService.run();
  const sweep = await evalService.thresholdSweep();
  const outDir = path.join(process.cwd(), "docs", "eval");
  fs.mkdirSync(outDir, { recursive: true });

  const md = `# Threshold curve

Generated by \`pnpm eval:sweep\`.

## Current policy

- Policy id: \`${GUARD_CONFIG.policyId}\`
- Similarity floor: \`${GUARD_CONFIG.similarityThreshold}\`
- Confidence floor: \`${GUARD_CONFIG.confidenceThreshold}\`

## Labeled eval

- Grounded accuracy: **${report.groundedAccuracy.toFixed(2)}**
- Citation precision: **${report.citationPrecision.toFixed(2)}**
- Refusal recall: **${report.refusalRecall.toFixed(2)}**

## Best sweep point

- Similarity: \`${sweep.best.similarityThreshold}\`
- Grounded recall: **${sweep.best.groundedRecall.toFixed(2)}**
- Refusal recall: **${sweep.best.refusalRecall.toFixed(2)}**

## Sweep table

| sim | grounded recall | refusal recall |
|---|---:|---:|
${sweep.points
  .map(
    (point) =>
      `| ${point.similarityThreshold.toFixed(2)} | ${point.groundedRecall.toFixed(2)} | ${point.refusalRecall.toFixed(2)} |`
  )
  .join("\n")}
`;

  fs.writeFileSync(path.join(outDir, "threshold-curve.md"), md);
  fs.writeFileSync(path.join(outDir, "latest.json"), JSON.stringify({ report, sweep }, null, 2));
  console.log(JSON.stringify({ groundedAccuracy: report.groundedAccuracy, best: sweep.best }, null, 2));
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
